{% set name = "bsplines2d" %}
{% set version = "0.0.22" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bsplines2d-{{ version }}.tar.gz
  sha256: 752aeedbfc79f9427d5a6c1d2a3ccb14d34f554f0f1c2051cfeab38b06ee2d11

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=40.8.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - matplotlib-base
    - datastock >=0.0.54

test:
  imports:
    - bsplines2d
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ToFuProject/bsplines2d
  summary: A python library for generic multidimensional bsplines on various meshes, using datastock
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Didou09
